FROM node:22.6.0-alpine

ARG ENVIRONMENT_NAME
ARG BRANCH_NAME

ENV ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
ENV BRANCH_NAME=${BRANCH_NAME}

WORKDIR /app

COPY .output /app/.output

EXPOSE 3000

CMD ["node", "/app/server/index.mjs"]
